plugins {
    id "com.android.application"
}

android {
    namespace "com.mnatool.yunjutongprobe"
    compileSdk 34

    defaultConfig {
        applicationId "com.mnatool.yunjutongprobe"
        minSdk 23
        targetSdk 34
        versionCode 12
        versionName "0.1.11"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

dependencies {
    testImplementation "junit:junit:4.13.2"
    testImplementation "org.json:json:20231013"
}
